### ISSUE TITLE
Document Realms Info Center Project

### ISSUE THREAD

**Issue by FueledByOCHD** [Ancient-Majik-Tech/RealmsInfoCenter#1]
# **Issue Info**

- **Name:** Document Realms Info Center Project
- **Type:** Live Update Tasks
- [Issue](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/issues/1)
	- [Inner](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Issues/Inner/Issue-1.md)
- **ProjectID:** Realms.Info.Hub
- **Systems:**
	- All
- **Features:**
	- All

---

## **Desc**

This Live Update issue is used to track the addition of the [AMT](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Company/Anceint%20Majik%20Tech.md)'s [Realms Info Center](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Info/Realms%20Info%20Center/Realms%20Info%20Center%20Project.md) project, used to give public infomation, to the Realms Infomation Center. It will also be used to document features and other concepts used by us.

For more Infomation on Live Updates Please check out [Issues Home](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Issues/Issues%20Home.md), and to get a better understanding of Inner Issues please check [Inner Issues Home](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Issues/Inner/Inner%20Issues%20Home.md) for more infomation.

This issue will bring all the new information from my personal account's repo, but will be bringing it up to 2.0.0.0 with a new and better layout hopefully.

This issue will continue to get updated until finished.

---

## **Tasks**

- Project
	
	- [x] Add [Readme](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/README.md) page
		- [x] Outline
		- [x] Apply
	- [ ] Add [Home](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Home.md) Page
		- [x] Outline
		- [x] Apply
	- [ ] Add Info Center Tracking Library
		- [x] [Repo](https://github.com/Ancient-Majik-Tech/RealmsInfoCenterTracking)
		- [ ] CSharp Library
		- [ ] ID Objects
		- [ ] Compliance
		- [ ] Build
		- [ ] Release  
	- **Layouts System**
		- [ ] Add [Realms Design Layout](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Layouts/Realms%20Design%20Layout/Realms%20Design%20Layout.md) project page
			- [x] outline
			- [ ] Apply
	- **Templates System**
		- [x] Add [Basic Page Template](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Templates/Basic%20Page%20Template.md)
			- [x] Outline
			- [x] Apply
		- [x] Add [Project Page Template](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Templates/Projects/Project%20Page%20Template.md)
			- [x] Outline
			- [x] Apply
		- [x] Add [Basic Issue Template](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Templates/Issues/Basic%20Issue%20Template.md)
			- [x] Outline
			- [x] Apply
		- [x] Add [Project Releases Template](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Templates/Projects/Project%20Releases%20Template.md)
			- [x] Outline
			- [x] Apply
			- [x] Add [Release Version Template](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Templates/Projects/Release%20Version%20Template.md)
				- [x] outline
				- [x] apply
		- [ ] Add [Links Page Template](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Templates/Projects/Project%20Page%20Template.md)
			- [x] outline
			- [ ] apply
		- [x] Add [System Page Template](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Templates/Projects/System%20Page%20Template.md)
			- [x] outline
			- [x] apply
			- [x] Add [Feature Template](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Templates/Projects/Feature%20Template.md)
				- [x] outline
				- [x] apply
		- [x] Add Objects Feature
			- [ ] Add [Data Structure Template](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Templates/Projects/Objects/Data%20Structure%20Template.md)
				- [x] outline
				- [ ] apply
			- [ ] Add [Data Outline Template](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Templates/Projects/Objects/Data%20Outline%20Template.md)
				- [x] outline
				- [ ] apply
			- [ ] Add [Object Template](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Templates/Projects/Objects/Object%20Template.md )
				- [x] outline
				- [ ] apply
			- [ ] Add [Tracker Template](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Templates/Projects/Objects/Tracker%20Template.md)
				- [x] outline
				- [ ] apply
			- [ ] Add [State Template](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Templates/Projects/Objects/State%20Template.md)
				- [x] outline
				- [ ] apply
	- **Projects System**
		- [ ] Add [Projects Home](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Projects%20Home.md) page
			- [x] Outline
			- [ ] Apply
		- [ ] add [Work In Progress](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Work%20In%20Progress.md) page
			- [x] Outline
			- [ ] Apply
		- [ ] Add Tracking Library Feature
			- [ ] Outline
			- [ ] Apply
		- [x] Add [Realms Info Center Project](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Info/Realms%20Info%20Center/Realms%20Info%20Center%20Project.md) page
			- [x] Outline
			- [x] Apply
			- [ ] Document Systems
				- [ ] [Lore System](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Info/Realms%20Info%20Center/Systems/Lore%20System.md)
					- [x] outline
					- [ ] apply
				- [ ] [Quick Links System](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Info/Realms%20Info%20Center/Systems/Quick%20Links%20System.md)
					- [x] outline
					- [ ] apply
				- [ ] [Inline Reference System](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Info/Realms%20Info%20Center/Systems/Inline%20References%20System.md)
					- [x] outline
					- [ ] apply
				- [ ] [Projects System](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Info/Realms%20Info%20Center/Systems/Projects%20System.md)
					- [x] outline
					- [ ] apply
				- [ ] [Templates System](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Info/Realms%20Info%20Center/Systems/Templates%20System.md)
					- [x] outline
					- [ ] apply
				- [ ] [Tutorials System](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Info/Realms%20Info%20Center/Systems/Tutorials%20System.md)
					- [x] outline
					- [ ] apply
				- [ ] [Updates System](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Info/Realms%20Info%20Center/Systems/Updates%20System.md)
					- [x] outline
					- [ ] apply
				- [ ] [Layouts System](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Info/Realms%20Info%20Center/Systems/Layouts%20System.md)
					- [x] outline
					- [ ] apply
			- [x] Add [Realms Info Center Releases](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Updates/Releases/Projects/Info/Realms%20Info%20Center%20Releases.md) page
				- [x] outline
				- [x] apply
	- **Quick Navi System**
		- [ ] Add [Links Home](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Links/Links%20Home.md) page
			- [x] outline
			- [ ] apply
		- [ ] Update to show new pages
			- [ ] Main
				- [x] outline
				- [ ] apply
			- [ ] Projects
				- [x] outline
				- [ ] apply
			- [ ] Templates
				- [x] outline
				- [ ] apply
			- [ ] Tutorial
				- [x] outline
				- [ ] apply
			- [ ] Updates
				- [x] outline
				- [ ] apply
	- [ ] Update Updates System
		- [ ] Add [Updates Home](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Updates/Updates%20Home.md) page
			- [x] Outline
			- [ ] Apply
		- [ ] new Live Update Tasks Feature
			- [ ] Outline
			- [ ] Apply
			- [ ] Add [Home](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Updates/Live%20Updates/Issues%20Home.md) page
				- [x] Outline
				- [ ] Apply
			- [x] new [Live Update Desc Template]()
				- [x] Outline
				- [x] Apply
				- [x] Update [Basic Issue Template](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Templates/Issues/Basic%20Issue%20Template.md) 
		- [ ] Add Dev Log Feaure
			- [ ] Outline
			- [ ] Apply
			- [ ] Overhaul
			- [ ] Add [Home](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Updates/Dev%20Log/Weekly%20Development%20Log.md) page
				- [x] Outline
				- [ ] Apply
		- [ ] Add Releases Feature
			- [x] Outline
			- [ ] Apply
			- [x] Overhaul
			- [ ] Add [Home](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Updates/Releases/Releases%20Home.md) page
				- [x] Outline
				- [ ] Apply
			- [ ] Core Libraries
				- [ ] Realms Core
					- [x] Outline
					- [ ] Apply
			- [x] Main
				- [x] [Project Realms](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Updates/Releases/Projects/Main/Project%20Realms%20Releases.md)
					- [x] Outline
					- [ ] Apply
			- [ ] Info
				- [x] [Realms Info Center](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Info/Realms%20Info%20Center/Realms%20Info%20Center%20Project.md)
					- [x] Outline
					- [x] Apply
				- [ ] Discord
					- [ ] Outline
					- [ ] Apply
				- [ ] Patreon
					- [ ] Outline
					- [ ] Apply
		- Update Dev Report Feature
			- [ ] Document
	- [ ] New [Issues System](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Info/Realms%20Info%20Center/Systems/Issues%20System.md)
		- [x] Outline
		- [ ] Apply
		- [x] Update Project Page
		- [x] Update Project Release Page
		- [ ] new Main Home Feature
			- [ ] Outline
			- [ ] Apply
			- [ ] new [Issues Home](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Issues/Issues%20Home.md) Page
				- [x] Outline
				- [ ] Apply
		- [ ] new Inner Issues Feature
			- [ ] Outline
			- [ ] Apply
			- [ ] new [Inner Issues Home](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Issues/Inner/Inner%20Issues%20Home.md) Page
				- [x] Outline
				- [ ] Apply
		- [ ] new Github Issue System
			- [ ] Outline
			- [ ] Apply
			- [x] new [Basic Issue Template](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Templates/Issues/Basic%20Issue%20Template.md)
				- [x] Outline
				- [x] Apply

---
