### ISSUE TITLE
Document Project Realms

### ISSUE THREAD

**Issue by FueledByOCHD** [Ancient-Majik-Tech/RealmsInfoCenter#2]
# **Issue Info**

- **Name:** Document Project Realms
- **Type:** Live Update Tasks
- [Issue][Issue Page]
	- [Inner][Page InnerUpdate]
- **ProjectID:** Realms.Main
- **Systems:**
	- All
- **Features:**
	- All

---

## **Desc**

This Live Update issue is used to track the addition of the [AMT][Page CompanyHome]'s [Project Realms][Project Realms] project, used to give public infomation, to the Realms Infomation Center. It will also be used to document features and other concepts used by us.

---

## **Tasks**

[Issue Page]: https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/issues/2

[Page InnerUpdate]: https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Updates/Live%20Updates/Inner/Issue-2.md

[Page RealmsRelease]: https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Updates/Releases/Projects/Main/Project%20Realms%20Releases.md
[Page CompanyHome]: https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Company/Anceint%20Majik%20Tech.md

[Project Realms]: https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Main/Project%20Realms.md

[System ProjectDesign]: https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Layouts/Realms%20Design%20Layout/Realms%20Design%20Layout%20Project.md

[Template ProjectPage]: https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Templates/Projects/Project%20Page%20Template.md
[Template ReleasePage]: https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Templates/Projects/Releases/Project%20Releases%20Template.md
[Template ReleaseVersionSection]: https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Templates/Projects/Releases/Release%20Version%20Template.md
[Template SystemPage]: https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Templates/Projects/Systems/System%20Page%20Template.md
[Template FeatureDoc]: https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Templates/Projects/Systems/Features/Feature%20Documentation%20Template.md
[Template ObjectStructure]: https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Templates/Projects/Systems/Features/Objects/Data%20Structure%20Template.md
[Template DataOutline]: https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Templates/Projects/Systems/Features/Objects/Data%20Outline%20Template.md
[Template Object]: https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Templates/Projects/Systems/Features/Objects/Object%20Template.md
[Template TrackerDoc]: https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Templates/Projects/Systems/Features/Objects/Tracker%20Template.md
[Template ObjectState]: https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Templates/Projects/Systems/Features/Objects/State%20Template.md

- Project
	- [x] Outline Project
	- [ ] Document Project
	- [ ] Add basic pages
		- [ ] Add [Project Realms][Project Realms] page
			- [x] Outline
			- [ ] Apply
		- [ ] Add [Project Realms Releases][Page RealmsRelease] page
			- [x] Outline
			- [ ] Apply
	- [ ] Document Systems
		- [ ] new [Project Design System][System ProjectDesign]
			- [x] Outline
			- [ ] Apply
			- [ ] new  [Project Page Template][Template ProjectPage] template
				- [x] Outline
				- [x] Apply
		- [ ] new Releases System
			- [ ] Outline
			- [ ] Apply
			- [x] new [Project Releases Template][Template ReleasePage] template
				- [x] Outline
				- [x] Apply
				- [ ] Document
			- [x] Add [Release Version Template][Template ReleaseVersionSection] template
				- [x] Outline
				- [x] Apply
				- [ ] Document
		- [ ] New Logic Based Design System
			- [ ] Outline
			- [ ] Apply
			- [ ] new Logic Systems Feature
				- [ ] Outline
				- [ ] Apply
				- [ ] New [System Page Template][Template SystemPage] template
					- [x] Outline
					- [x] Apply
					- [ ] Document
			- [ ] new System Data Feature 
				- [ ] Outline
				- [ ] Apply
				- [ ] New [Feature Documentation Template][Template FeatureDoc]
					- [x] Outline
					- [x] Apply
					- [ ] Document
				- [ ] Add [Data Structure Template][Template ObjectStructure]
					- [x] outline
					- [ ] apply
				- [ ] Add [Data Outline Template][Template DataOutline]
					- [x] outline
					- [ ] apply
				- [ ] Add [Object Template][Template Object]
					- [x] outline
					- [ ] apply
				- [ ] Add [State Template][Template ObjectState]
					- [x] outline
					- [ ] apply
		- [ ] new Code Tracking System
			- [ ] Outline
			- [ ] Apply
			- [ ] new Sharp Link Feature
				- [ ] Outline
				- [ ] Apply
				- [ ] Add [Tracker Documentation Template][Template TrackerDoc]
					- [x] outline
					- [ ] apply

---
