### ISSUE TITLE
Document Realms Core Project

### ISSUE THREAD

**Issue by FueledByOCHD** [Ancient-Majik-Tech/RealmsInfoCenter#3]
# **Issue Info**

- **Name:** Document Realms Core Project
- **Type:** Live Update Tasks
- [Issue](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/issues/3)
	- [Inner](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Issues/Inner/Issue-3.md)
- **ProjectID:** Realms.Core
- **Systems:**
	- All
- **Features:**
	- All

---

## **Desc**

This Live Update issue is used to track the addition of the [AMT](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Company/Anceint%20Majik%20Tech.md)'s [Realms Core](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Core%20Libraries/Realms%20Core/Realms%20Core%20Project.md) project, used to give public infomation, to the Realms Infomation Center. It will also be used to document features and other concepts used by us.

For more Infomation on Live Updates Please check out [Issues Home](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Issues/Issues%20Home.md), and to get a better understanding of Inner Issues please check [Inner Issues Home](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Issues/Inner/Inner%20Issues%20Home.md) for more infomation.

---

## **Tasks**

- Project
	- [ ] Add [Project](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Core%20Libraries/Realms%20Core/Realms%20Core%20Project.md) page
		- [x] outline
		- [ ] apply
	- [ ] Add Project [Release](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Updates/Releases/Projects/Core%20Libraries/Realms%20Core%20Releases.md) Page
		- [x] outline
		- [ ] apply
	- [ ] Add Project ID Object
		- [x] Add IDs
		- [ ] Apply Trackers
	- [ ] Apply [Realms Design Layout](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Layouts/Realms%20Design%20Layout/Realms%20Design%20Layout.md)
		- [ ] Design
			- [ ] Apply Realms Project Design Layout
			- [ ] Apply Realms Logic Systems Design Layout
		- [ ] Coding
			- [ ] Trackers
				- [ ] Apply Project Tracking Layout
	- Overhaul [Design System](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Core%20Libraries/Realms%20Core/Systems/Design%20System.md) 
		- [x] Create System ID Object
		- [ ] Complete Overhaul To 2.0.0.0 Full Layout

---
