### ISSUE TITLE
Document Realms Design Layout Project

### ISSUE THREAD

**Issue by FueledByOCHD** [Ancient-Majik-Tech/RealmsInfoCenter#4]
# **Project Info**

- **ProjectID:** Realms.Layouts.Main
- **Systems:**
	- All
- **Features:**
	- All

---

## **Desc**

This issue is used to keep track of tasks for [Realms Design Layout](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Layouts/Realms%20Design%20Layout/Realms%20Design%20Layout.md) project.

---

## **Tasks**

- Project
	- [ ] Add [Project](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Layouts/Realms%20Design%20Layout/Realms%20Design%20Layout%20Project.md) page
		- [x] Outline
		- [ ] Apply
	- [ ] Add [Releases](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Updates/Releases/Projects/Layouts/Realms%20Design%20Layout%20Releases.md) page
		- [x] Outline
		- [ ] Apply
	- [ ] Document Systems
		- [ ] [Projects](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Layouts/Realms%20Design%20Layout/Systems/Projects%20System.md)
			- [x] Outline
			- [ ] Apply
		- [ ] [Coding](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Layouts/Realms%20Design%20Layout/Systems/Coding%20System.md)
			- [x] Outline
			- [ ] Apply
		- [ ] [Info](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Layouts/Realms%20Design%20Layout/Systems/Info%20System.md)
			- [x] Outline]()
			- [ ] Apply
		- [ ] [Agreements](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Layouts/Realms%20Design%20Layout/Systems/Agreements%20System.md)
			- [x] Outline
			- [ ] Apply
		- [ ] [Issues](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Layouts/Realms%20Design%20Layout/Systems/Issues%20System.md)
			- [x] Outline
			- [ ] Apply
		- [ ] [Content](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Layouts/Realms%20Design%20Layout/Systems/Content%20System.md)
			- [x] Outline
			- [ ] Apply

---
