### ISSUE TITLE
Document Ancient Majik Tech Company Project

### ISSUE THREAD

**Issue by FueledByOCHD** [Ancient-Majik-Tech/RealmsInfoCenter#5]
# **Issue Info**

- **Name:** Document Ancient Majik Tech Company Project
- **Type:** Live Update Tasks
- [Issue](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/issues/5)
	- [Inner](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Issues/Inner/Issue-5.md)
- **ProjectID:** Realms.Layouts.Main
- **Systems:**
	- All
- **Features:**
	- All

---

## **Desc**

This Live Update issue is used to track the addition of the [AMT](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Company/Anceint%20Majik%20Tech.md)'s [AMT Company](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Company/Anceint%20Majik%20Tech.md) project, used to give public infomation, to the Realms Infomation Center. It will also be used to document features and other concepts used by us.

For more Infomation on Live Updates Please check out [Issues Home](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Issues/Issues%20Home.md), and to get a better understanding of Inner Issues please check [Inner Issues Home](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Issues/Inner/Inner%20Issues%20Home.md) for more infomation.

---

## **Tasks**

- Project
	- [ ] add [Project](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Company/Anceint%20Majik%20Tech.md) Page
		- [x] Outline
		- [x] Apply
		- [ ] Systems
	- [x] add [Releases](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Updates/Releases/Projects/Company/AMT%20Releases.md) page
		- [x] Outline
		- [x] Apply
	- [ ] new [Info System](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Company/Systems/Info%20System.md)
		- [x] Outline
		- [x] Apply
		- [ ] Features
		- [x] new Project Info Feature
			- [x] Outline
			- [x] Apply
		- [ ] new Company Home Feature
			- [x] Outline
			- [ ] Apply
		- [ ] new Info Center Feature
			- [x] Outline
			- [ ] Apply
		- [ ] new Updates Feature
			- [x] Outline
			- [ ] Apply
	- [ ] new [Teams System](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Company/Systems/Teams%20System.md)
		- [x] Outline
		- [ ] Apply
		- [ ] new Management Team Feature
			- [ ] Outline
			- [ ] Apply
		- [ ] new Core Libraries Feature
			- [ ] Outline
			- [ ] Apply
	- [ ] new [Issues System](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Company/Systems/Issues%20System.md)
		- [x] Outline
		- [ ] Apply
		- [ ] new Issue Tags Feature
			- [ ] Outline
			- [ ] Apply
			- [x] Create [Tags](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/labels)
			- [ ] Document Tags
		- [ ] new Basic Templates Feature
			- [ ] Outline
			- [ ] Apply
			- [x] [Template](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Templates/Issues/Basic%20Issue%20Template.md)
		- [ ] new Live Update Issues Feature
			- [ ] Outline
			- [ ] Apply
			- [x] [Template](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Templates/Issues/Live%20Update%20Desc%20Template.md)
			- [x] Project Realms
				- [x] Main
					- [Project Realms](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Main/Project%20Realms.md)
						- [x] [Issue](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/issues/2)
							- [x] [Inner](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Issues/Inner/Issue-2.md)
				- [x] [Company](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Company/Anceint%20Majik%20Tech.md)
					- [x] This
						- [x] [Issue](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/issues/5)
							- [x] [Inner](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Issues/Inner/Issue-5.md)			
				- [ ] Core Libraries
					- [x] [Realms Core](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Core%20Libraries/Realms%20Core/Realms%20Core%20Project.md)
						- [x] [Issue](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/issues/3)
							- [x] [Inner](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Issues/Inner/Issue-3.md)
					- [ ] Realms Editor Core
						- [ ] Issue
						- [ ] Inner Issue
					- [ ] Realms Math Core
						- [ ] Issue
						- [ ] Inner Issue
					- [ ] Realms Interops Core
						- [ ] Issue
						- [ ] Inner Issue
					- [ ] Realms Graphics Core
						- [ ] Issue
						- [ ] Inner Issue
					- [ ] Realms SDL Core
						- [ ] Issue
						- [ ] Inner Issue
					- [ ] Realms Users Core
						- [ ] Issue
						- [ ] Inner Issue
					- [ ] Realms Sound Core
						- [ ] Issue
						- [ ] Inner Issue
				- [ ] Engine
					- [ ] Realms Engine
				- [ ] Info
					- [x] [Realms Info Center](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Info/Realms%20Info%20Center/Realms%20Info%20Center%20Project.md)
						- [x] [Issue](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/issues/1)
							- [x] [Inner](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Issues/Inner/Issue-1.md)
					- [ ] Discord Server
						- [ ] Issue
						- [ ] Inner Issue
					- [ ] Patreon Page
						- [ ] Issue
						- [ ] Inner Issue
				- [x] Layouts
					- [x] [Realms Design Layout](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Layouts/Realms%20Design%20Layout/Realms%20Design%20Layout%20Project.md)
						- [x] [Issue](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/issues/5)
							- [x] [Inner](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Issues/Inner/Issue-5.md)
				- [x] Content
					- [x] [Realms Design Layout Templates Package](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Layouts/Realms%20Design%20Layout%20Templates%20Package/Realms%20Design%20Layout%20Templates%20Package%20Project.md) Project
						- [x] [Issue](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/issues/6)
							- [x] [Inner](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Issues/Inner/Issue-6.md)
	- [ ] new [Applictions System](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Company/Systems/Applications%20System.md)
		- [x] Outline
		- [ ] Apply
		- [ ] new Team Feature
			- [ ] Outline
			- [ ] Apply
		- [ ] new Submission Feature
			- [ ] Outline
			- [ ] Apply
		- [ ] new Issue Feature
			- [ ] Outline
			- [ ] Apply
		- [ ] new Volenteer Feature
			- [ ] Outline
			- [ ] Apply
		- [ ] new Third Party Content Feature
			- [ ] Outline
			- [ ] Apply
	- [ ] new [Users System](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Company/Systems/Users%20System.md)
		- [x] Outline
		- [ ] Apply
		- [ ] new Tiers Feature
			- [ ] Outline
			- [ ] Apply
		- [ ] new Monthly Dontations Feature
			- [ ] Outline
			- [ ] Apply
		- [ ] new In-App Management Feature
			- [ ] Outline
			- [ ] Apply
		- [ ] new Content Packages Feature
			- [ ] Outline
			- [ ] Apply
	- [ ] new [Servers System](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Company/Systems/Servers%20System.md)
		- [x] Outline
		- [ ] Apply
		- [ ] new Events Driven Feature
			- [ ] Outline
			- [ ] Apply
		- [ ] new Users Feature
			- [ ] Outline
			- [ ] Apply
		- [ ] new Chat Feature
			- [ ] Outline
			- [ ] Apply
		- [ ] new Activations Feature
			- [ ] Outline
			- [ ] Apply
		- [ ] new Packages Feature
			- [ ] Outline
			- [ ] Apply
	- [ ] new [Volunteer System](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Company/Systems/Volunteer%20System.md)
		- [x] Outline
		- [ ] Apply
	- [ ] new [Third Party System](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Company/Systems/Third%20Party%20System.md)
		- [x] Outline
		- [ ] Apply
		- [ ] new Content Types Feature
			- [ ] Outline
			- [ ] Apply
		- [ ] new Submission Feature
			- [ ] Outline
			- [ ] Apply
		- [ ] new Compliance Feature
			- [ ] Outline
			- [ ] Apply
	- [x] new [Legal System](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Company/Systems/Legal%20System.md)
		- [x] Outline
		- [ ] Apply
		- [ ] new Realms User Agreement Feature
			- [ ] Outline
			- [ ] Apply
		- [ ] new Legal Status Feature
			- [ ] Outline
			- [ ] Apply
	- [ ] new [Source Repos System](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Company/Systems/Source%20Repos%20System.md)
		- [x] Outline
		- [ ] Apply
		- [ ] new Realms Project Feature
			- [ ] Outline
			- [ ] Apply
		- [ ] new Project Source Feature
			- [ ] Outline
			- [ ] Apply
		- [ ] new Repo Pages Feature
			- [ ] Outline
			- [ ] Apply
		- [ ] new Public Documenation Feature
			- [ ] Outline
			- [ ] Apply
			- [ ] Info Center
				- [x] Project
				- [ ] Systems
				- [x] Releases
				- [ ] Templates
				- [ ] Tracking
				- [ ] Compliance
			- [ ] Realms Core
				- [x] Project
				- [ ] Systems
				- [x] Releases
				- [ ] Templates
				- [ ] Tracking
				- [ ] Compliance
			- [ ] Project Realms
				- [x] Project
				- [ ] Systems
				- [x] Releases
				- [ ] Templates
				- [ ] Tracking
				- [ ] Compliance
			- [ ] Patreon
				- [ ] Project
				- [ ] Systems
				- [ ] Releases
				- [ ] Templates
				- [ ] Tracking
				- [ ] Compliance
			- [ ] Discord
				- [ ] Project
				- [ ] Systems
				- [ ] Releases
				- [ ] Templates
				- [ ] Tracking
				- [ ] Compliance
			- [ ] Realms Design Layout
				- [x] Project
				- [ ] Systems
				- [x] Releases
				- [ ] Templates
				- [ ] Tracking
				- [ ] Compliance
			- [ ] Realms Design Layout Templates Package
				- [x] Project
				- [ ] Systems
				- [x] Releases
				- [ ] Templates
				- [ ] Tracking
				- [ ] Compliance
	- [ ] new [Github Orgonization System](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Company/Systems/Github%20Orgonization%20System.md)
		- [x] Outline
		- [ ] Apply
		- [x] [Github](https://github.com/Ancient-Majik-Tech)
		- [ ] new Main Project Feature
			- [ ] Outline
			- [ ] Apply
			- [ ] [Project Realms](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Main/Project%20Realms.md)
				- [x] Outline
				- [ ] Apply
				- [x] Project
				- [x] [Repo](https://github.com/Ancient-Majik-Tech/Project-Realms)
				- [ ] Systems
				- [x] [Releases](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Updates/Releases/Projects/Main/Project%20Realms%20Releases.md)
		- [ ] new Info Projects Feature
			- [ ] Outline
			- [ ] Apply		
			- [ ] [Info Center](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Home.md)
				- [x] Outline
				- [ ] Apply
				- [x] [Repo](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter)
				- [x] [Project](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Info/Realms%20Info%20Center/Realms%20Info%20Center%20Project.md)
				- [ ] Systems
				- [x] [Releases](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Updates/Releases/Projects/Info/Realms%20Info%20Center%20Releases.md)
		- [ ] new Layouts Projects Feature
			- [ ] Outline
			- [ ] Apply
			- [ ] [Realms Design Layout](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Layouts/Realms%20Design%20Layout/Realms%20Design%20Layout%20Project.md)
				- [x] Outline
				- [ ] Apply
				- [x] Repo
				- [x] Project
				- [ ] Systems
				- [x] [Releases](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Updates/Releases/Projects/Layouts/Realms%20Design%20Layout%20Releases.md)
			- [ ] Content
				- [ ] [Realms Design Layout Templates Package](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Layouts/Realms%20Design%20Layout%20Templates%20Package/Realms%20Design%20Layout%20Templates%20Package%20Project.md)
					- [x] Outline
					- [ ] Apply
					- [x] [Repo](https://github.com/Ancient-Majik-Tech/RealmsDesignLayoutTemplates)
					- [x] Project
					- [ ] Systems
					- [x] [Releases](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Updates/Releases/Projects/Layouts/Realms%20Design%20Layout%20Templates%20Package%20Releases.md)
		- [ ] new Project Repos Feature
			- [ ] Outline
			- [ ] Apply
			- [ ] [Project Realms](https://github.com/Ancient-Majik-Tech/Project-Realms)
				- [x] Main
				- [ ] Company
					- [x] [Company Management Repo](https://github.com/Ancient-Majik-Tech/AMTManagement)
				- [x] Info
					- [x] [Info Center](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter)
				- [ ] Core Libraries
					- [x] [Realms Core](https://github.com/Ancient-Majik-Tech/Realms-Core)
				- [x] Layouts
					- [x] [Realms Design Layout](https://github.com/Ancient-Majik-Tech/RealmsDesignLayout)
				- [ ] Content
					- [x] [Realms Design Layout Templates Package](https://github.com/Ancient-Majik-Tech/RealmsDesignLayoutTemplates)
	- [ ] new [Builds System](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Company/Systems/Builds%20System.md)
		- [x] Outline
		- [ ] Apply
		- [ ] new Private Dev Feature
			- [ ] Outline
			- [ ] Apply
		- [ ] new Beta Feature
			- [ ] Outline
			- [ ] Apply
		- [ ] new Early Public Feature
			- [ ] Outline
			- [ ] Apply
		- [ ] new Public Feature
			- [ ] Outline
			- [ ] Apply
	- [ ] new [Updates System](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Company/Systems/Updates%20System.md)
		- [x] Outline
		- [ ] Apply
		- [ ] [Home Page](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Updates/Updates%20Home.md) Feature
			- [x] Outline
			- [ ] Apply
		- [ ] [Links](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Links/Updates%20Links.md) Feature
			- [x] Outline
			- [ ] Apply
		- [ ] new Weekly Development Log Feature
			- [ ] Outline
			- [ ] Apply
			- [ ] Home Page
			- [ ] Overhaul
			- [x] Live
			- [ ] Delete [Old](https://github.com/FueledByOCHD/Realms-Info-Center) repo
		- [ ] new Weekly Development Plan Feature
			- [ ] Outline
			- [ ] Apply
			- [x] [Live](https://github.com/FueledByOCHD/Realms-Info-Center/blob/develop/Updates/Weekly%20Development%20Log/Weekly%20Updates%20Home.md)
			- [ ] Overhaul
	- [ ] new [Layouts System](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Company/Systems/Layouts%20System.md)
		- [x] Outline
		- [ ] Apply
		- [x] [Project Page](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Layouts/Realms%20Design%20Layout/Realms%20Design%20Layout%20Project.md)
			- [x] [Templates Package](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Layouts/Realms%20Design%20Layout%20Templates%20Package/Realms%20Design%20Layout%20Templates%20Package%20Project.md)
	- [ ] new [Lore System](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Company/Systems/Lore%20System.md)
		- [x] Outline
		- [ ] Apply
		- [ ] Overhaul
		- [ ] Home Page
	- [ ] new [Offical Content System](https://github.com/Ancient-Majik-Tech/RealmsInfoCenter/blob/main/Projects/Company/Systems/Offical%20Content%20System.md)
		- [x] Outline
		- [ ] Apply
		- [ ] new Games Feature
			- [ ] Outline
			- [ ] Apply
		- [ ] new Engine Feature
			- [ ] Outline
			- [ ] Apply
		- [ ] new Core Libraries Feature
			- [ ] Outline
			- [ ] Apply
		- [ ] new Modding Feature
			- [ ] Outline
			- [ ] Apply
		- [ ] new Tools Feature
			- [ ] Outline
			- [ ] Apply
		- [ ] new Lore Feature
			- [ ] Outline
			- [ ] Apply
		- [ ] new Content Package Feature
			- [ ] Outline
			- [ ] Apply

---
